### ISSUE TITLE
Thanos receive component umbrella issue

### ISSUE THREAD

**Issue by brancz** [thanos-io/thanos#1093]
This is an umbrella issue to track the development of the accepted [proposal for the Thanos receive component](https://github.com/improbable-eng/thanos/blob/master/docs/proposals/approved/201812_thanos-remote-receive.md).

* [x] remote-write protocol accepting API https://github.com/improbable-eng/thanos/pull/811
* [x] upload blocks produced by local tsdb https://github.com/improbable-eng/thanos/pull/1011 https://github.com/improbable-eng/thanos/pull/1046
* [x] hashring for sharded storage (as a start to not be blocked by the next item, we expect that all requests are sent to all receive nodes and they persist only the time-series assigned to them) https://github.com/improbable-eng/thanos/pull/1217
* [x] split and forward requests for time-series to receive nodes according to hashring https://github.com/improbable-eng/thanos/pull/1243
* [x] create mechanism to force flush and upload, while not accepting writes (necessary for hashring resizing)
* [x] announce multiple sets of external labels through StoreAPI info response #1284 (this does not only influence the receive component, but will also allow sharding distinct sets of blocks by the store component as well, in addition to time sharding as introduced by https://github.com/improbable-eng/thanos/pull/1077)
* [x] add management of multiple tsdb instances based on write request header input
* [x] dynamo style replication and read/write quorum. This was only part of the "Open Questions" in the design doc, but it is becoming increasingly clear that this will need to be necessary, but likely still the last thing to implement. https://github.com/improbable-eng/thanos/pull/1270
* [x] component documentation

Let me know if any of this is unclear or needs more detail, should the design doc not have enough.

@bwplotka @domgreen @povilasv @metalmatze @squat @mxinden @paulfantom @s-urbaniak

**Comment by bwplotka** [comment]
I think it would be nice to also document the `receive` like we do for other commands here: https://thanos.io/getting-started.md/

**Comment by dawidmalina** [comment]
@bwplotka what is actual state of the receive implementation? I mean how far we are from having this ready for wider audience (at least for test purpose)?

**Comment by dawidmalina** [comment]
Good to hear that 👍 but I'm still suspicious about definition of the word "everything". According to the number of todo tasks attached to this ticket we have only one topic related to management of multiple tsdb instances. Is this the only one to consider receive implementation "ready for a wider audience" or we still rather stay away and wait until other features will be implemented?

**Comment by brancz** [comment]
Sorry I meant everything on this list. “Other features” refers to things that we may only discover as we use this more intensely :)

**Comment by bwplotka** [comment]
I think we should slowly consider making the receiver a non-experimental component. 

I know multi-tsdb support is still in progress, plus docs (edited the description to add that point), but we are having feedback that receiver is quite stable for users already: https://cloud-native.slack.com/archives/CK5RSSC10/p1575471712121900 so worth to either reconsider making in stable now with some docs or to helpe with multi-tsdb work (:

**Comment by brancz** [comment]
I've been working on the multi-tsdb work for some time, and I don't think there is a way to introduce it completely disruptionless, so I would prefer to not remove the experimental naming/labeling until we have the multi-tsdb work and have it sink in for a little bit. That said, we do already use this in prod, so while there may be manual migrations necessary, it's unlikely to break very badly at this point.

**Comment by kakkoyun** [comment]
Still in-progress.

**Comment by bwplotka** [comment]
Stale bot, go away for now (:

**Comment by brancz** [comment]
Actively working on finishing this :)

**Comment by dinesh4747** [comment]
@brancz - When can we expect Thanos Receiver docs and General availability just curious

**Comment by brancz** [comment]
The last feature feels fairly close to completion: https://github.com/thanos-io/thanos/pull/2012

After that we need to write comprehensive docs and I am expecting one configuration change in the hashring configuration, but I think it can be done in a backward compatible way.

**Comment by bwplotka** [comment]
I guess last part is missing only: **Docs** (:

**Comment by brancz** [comment]
We also know of some limitations on the way that series are routed through the hashring, causing every request to translate into N internal requests, which makes a hashring only scale to the number of requests a single node can handle (in terms of parsing, so CPU bound). We need to come up with a mechanism to split up requests across multiple hashrings other than just by tenant ID. I think we might be able to do that in a backward compatible way but we should think about it.

**Comment by kakkoyun** [comment]
For the docs https://github.com/thanos-io/thanos/issues/1093

**Comment by kakkoyun** [comment]
Initial component documentation is done. Also it's no longer marked as experimental. Shall we close this one?

**Comment by brancz** [comment]
Initial implementation is done. This component is being used a lot in various production environments already, so it's been battle tested in various ways already. That said there are two main things that I would like to get agreement on before taking it our of experimental state:

* https://github.com/thanos-io/thanos/pull/2675
* https://github.com/thanos-io/thanos/pull/2661

That said, I think this umbrella issue can be closed as all the initial features have been implemented. Thanks to everyone involved in this, it's been ~1.5years worth of work.
