### ISSUE TITLE
Umbrella issue for RW coordination for object storage.

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1528]
Agreed proposal: https://thanos.io/proposals/201901-read-write-operations-bucket.md/

![Diagram](https://docs.google.com/drawings/d/e/2PACX-1vSZjddrWBkf2ynczeIMSzGo-yqe7Cg9X-TG_LjyWAP_ToyZolMEG_UnbNlvoSetRhDLmlfABd_rJ4W9/pub?w=960&h=720)
 
## Action Items:

* [x] Ensure "consistency delay" (aka syncDelay)  is implemented on all components (handling fresh blocks) with the reasonable minimum value
     * Related: https://github.com/thanos-io/thanos/pull/1394
* [x] Ensure Store gateway handles `toDelete` blocks (detecting those and unloading before they are removed)
* [x] Implement handling of `HealthyOverlapped` block based on source ULIDs from meta file.
* [X] Delete should start from deleting meta.json ([done](https://github.com/thanos-io/thanos/pull/1525))
* [x] Add ScheduleDelete that will delete adding deletion-mark.json
* [x] Add deleteDelay support for compactor on apply on toDelete blocks.
* [ ] [Low] Save successful compactor block uploads to persistent file, same as shipper to avoid unnecessary duplicated compactions/downsamplings
* [ ] [Low] Add ignore_delay parameter that will ignore syncDelay for sudden repairs.
* [x] [Low] Ignore HealthyOverlapped to reduce resource consumption for store gateway.

**Comment by bwplotka** [comment]
cc @krasi-georgiev @mjudeikis

**Comment by jojohappy** [comment]
@bwplotka I'm interested to implement the proposal, could I start to do that?

**Comment by bwplotka** [comment]
Anyone is welcome to help. cc @abursavich as we talked about this today at KubeCon. Feel free to read the proposal: https://thanos.io/proposals/201901-read-write-operations-bucket.md/ It should be quite explanatory, even though a bit long. This issue description contains all tasks related to this. If you wish to start working on it I think we could join forces and finish it quickly, happy to jump on it finally as well.

**Comment by bwplotka** [comment]
Fixes: https://github.com/thanos-io/thanos/issues/564

**Comment by Masquerade0097** [comment]
Hi @bwplotka, I went through the proposal and I'm interested to implement it in the community bridge program. Please let me know if I can start working on it.

**Comment by palash25** [comment]
Hi @bwplotka I am also interested in the project. Since there are only two days left in the application period how are you going to select the mentee for this? Does one need to have previous contributions to thanos or a proposal on how to implement the project (like we do for GSoC) or both?

I am quite comfortable with Go with almost 2 years of experience writing it but distributed systems is something I have only begun to scratch the surface of and would like to get more experience in it. This seems like a perfect project for it.

Here is what I have done so far
- Built thanos locally
- Explored it a bit using the Katacode tutorial
- Went through the project proposal

Haven't been through the code yet, will do it in the next few hours.
I am looking for some guidance here on what to do next and proceed further with my application for community bridge any help would be appreciated. Thanks

**Comment by bwplotka** [comment]
Hi, Thanks for this @Masquerade0097 @palash25 ((: 

However, I am not the one who decides. The full project list will be finalized on Monday: https://github.com/cncf/soc/blob/master/communitybridge/README.md#timeline 

The CNCF will select projects and once the project will be selected, you will see it on the website and you will be able to apply as a mentee. Also cc @GiedriusS 

Have a nice weekend. (:

**Comment by palash25** [comment]
thanks

**Comment by bwplotka** [comment]
@palash25 @Masquerade0097  please apply for this as described here: https://docs.linuxfoundation.org/display/DOCS/Mentees

**Comment by palash25** [comment]
I did apply through the community bridge site @bwplotka

**Comment by bwplotka** [comment]
@khyatisoneji our Community Bridge student is on it (:

**Comment by bwplotka** [comment]
Still in doing.

**Comment by bwplotka** [comment]
This should be now done, thanks to @khyatisoneji https://github.com/thanos-io/thanos/pull/2136
