### ISSUE TITLE
Long Term Storage Improvements [Tracking Issue]

### ISSUE THREAD

**Issue by bwplotka** [thanos-io/thanos#1705]
This is the "index" issue to help to track issues, initiatives, and ideas to try that might improve the usage of **long term storage of metrics** for both read and storage part. It currently works, but there are many things we can improve. The goal of this ticket is to be more clear and give some overview of what’s happening and compare other potential improvement ideas! Targetted mostly to contributors who want to help us with some challenging problems.

 **Overall we want to encourage more collaboration and contributions on this! So please jump on anything interesting and propose new ideas! (:**

Let's keep the discussions about each idea in separate GitHub issue, if no GitHub issue is created, please create one and link it here if it relates to the problems we want to solve! I will try to have this issue updated once we progress.

## Store Gateway Syncing Blocks.

**Things to improve** 

* Reduce [startup network traffic](https://github.com/thanos-io/thanos/issues/664)
* Make startup faster
* Reduce [memory usage during startup](https://github.com/thanos-io/thanos/issues/448)
* Eventual [consistency](https://github.com/thanos-io/thanos/issues/564)

### Overview
<details>
  <summary>Click to see the current logic</summary>

The syncing might be the most impactful during startup, especially with empty local store Gateway directory, however, it is also performed every [3m minutes interval](https://github.com/thanos-io/thanos/blob/9c2fe0392a40cce0012f64ce297dfa1c51926f62/cmd/thanos/store.go#L54) (which is configurable by flag). This means that any improvements in syncing will improve both startup and overall baseline memory used.

The main goal of the block sync process is to allow Store Gateway to access the data in the form of blocks from object storage and allow returning it to Querier on `Series` gRPC request. The process looks as follows:

* Iterate over all blocks in object storage:
* For every not seen before block:
  * Download meta.json
     * skip if younger than consistency delay
     * skip if outside of time partition
     * skip if relabelling ignores the block (sharding)
  * Check if index-cache.json is present on the disk. IF not: 
     *  Download whole index file, mmap all of it (!)
    * Calculates index-cache.json
  * Load whole index-cache to memory
  * Remove non-existing blocks’ index-cache (index-header let’s call it) JSON files from disk. 

The mentioned [index-cache.json](https://github.com/thanos-io/thanos/blob/bd9aa1b4be3bb5d841cb7271c29d02ebb5eb5168/pkg/block/index.go#L40) (index-header) holds block’s:
* [TOC](https://github.com/prometheus/prometheus/blob/master/tsdb/docs/format/index.md#toc)
* [Symbols](https://github.com/prometheus/prometheus/blob/master/tsdb/docs/format/index.md#symbol-table)
* LabelValues:
  * Calculated from all [LabesIndicesTable](https://github.com/prometheus/prometheus/blob/master/tsdb/docs/format/index.md#label-offset-table), that each points to [LabelIndex](https://github.com/prometheus/prometheus/blob/master/tsdb/docs/format/index.md#label-index) entry.
  * Used for matching against request selectors. 
* [Postings Offsets](https://github.com/prometheus/prometheus/blob/master/tsdb/docs/format/index.md#postings-offset-table)

</details>

### Initiatives/Ideas 

* [ ] Switch to different format for disk index-cache [issue](https://github.com/thanos-io/thanos/issues/942)
  * e.g protobuf + compression for index-cache.json: [PR](https://github.com/thanos-io/thanos/pull/1013)
  * [json-iterator](https://github.com/json-iterator/go)
* [ ] Work purely on symbols instead of strings, only lookup strings afterwards.
* [ ] Fix regression introduced in v0.8: [issue](https://github.com/thanos-io/thanos/issues/1655)
* [ ] Mmap/load index header to memory on demand
* [ ] Optimize constructing index-cache from index: [issue](https://github.com/thanos-io/thanos/issues/1711)
* [ ] Make index more object storage friendly (: 

## Querying

**Things to improve**  

* Memory used
* [Store GW OOMs](https://github.com/thanos-io/thanos/issues/448)
* Querier OOMs

### Overview
<details>
  <summary>Click to see the current logic</summary>

So how the querying works in Thanos? The query is delivered through different components (top down):

* Optional Cortex response cacher
  * Time align
  * Split by day (!)
  * Caches response
* Querier
  * Performs PromQL evaluation
  * Fanouts to each StoreAPI
  * Merges all responses per sorted Series by Series
* Store Gateway
  *  Chooses blocks to query based on time, external labels and resolution
  * Per block:
    * Get matching postings in a [partitioned way](https://github.com/thanos-io/thanos/blob/64af185e73978986c7955d2b3e8ad49e33bb099c/pkg/store/bucket.go#L655).
    * Get series pointed by those postings in a [partitioned way](https://github.com/thanos-io/thanos/blob/64af185e73978986c7955d2b3e8ad49e33bb099c/pkg/store/bucket.go#L679)
    * [Choose](https://github.com/thanos-io/thanos/blob/64af185e73978986c7955d2b3e8ad49e33bb099c/pkg/store/bucket.go#L708) chunks within each series that matches time range within the block
    * Fetch chunks in a partitioned way 
  * Merge data in SeriesSet

Important facts: 

* We partition index data fetches in every step to combine multiple object storage `GetRange` fetches for the same index file into bigger requests to avoid rate limiting. This blocks a bit of streaming of fetching series, postings due to partitioning.

We currently don't cache anything on a disk other than index-cache.json mentioned in the Sync section.
</details>

### Initiatives/Ideas 

* Store GW:
  * [ ] Avoid startup; move to lazy block loading: [proposal](https://github.com/thanos-io/thanos/issues/1813)
  * [X] Time sharding
       * [ ] Auto time-sharding [discussion](https://cloud-native.slack.com/archives/CK5RSSC10/p1569839598197500)
  * [X] Block sharding: [proposal](https://github.com/thanos-io/thanos/pull/1501) 
  * [ ] Index Caching in memory:
    * [ ] Cache only per block.
    * [ ] Evict block’s items from the cache once block does not exist.
    * [ ] Use ristretto for caching instead of our naive LRU: [PR](https://github.com/thanos-io/thanos/pull/849)
    * [ ] Shared index across instances e.g with Memcache
  * [ ] Disk caching:
    * [ ] Sparse files: [issue](https://github.com/thanos-io/thanos/issues/1471), [proposal PR](https://github.com/thanos-io/thanos/pull/1567)
* [ ] Rate limit / Limit memory (we have some concurrency limits and sample limits currently)
    * We do that partially but we can be smarter about it e.g bytes/chunks, detect early.
    * Count allocations (roughly) per user/query: [proposal](https://github.com/thanos-io/thanos/pull/1747)
* [ ] StoreAPI: Split gRPC Series stream frames into smaller ones as recommended by gRPC. [todo](https://github.com/thanos-io/thanos/blob/9d4d0bf408ed86eaab371c8f0c52d7bb5fe6e164/cmd/thanos/query.go#L179)
* [X] Unify labels: [issue](prometheus/prometheus#6029) 
    * Intern labels cc @ppanyukov 
* Querier
  * [ ] Prevent knowingly bad queries
  * [ ] Response caching: [tracking issue](https://github.com/thanos-io/thanos/issues/1651)
  * [ ] Distributed Queries: [issue](https://github.com/thanos-io/thanos/issues/992)
  * [ ] Does splitting by day make even sense? Maybe split more as discussed [here](https://github.com/thanos-io/thanos/issues/1649)
  * Lax the StoreAPI.Series and merge more on Querier

### Initiatives/Ideas 

* [ ] Request logger [grpc middleware](https://github.com/grpc-ecosystem/go-grpc-middleware/pull/223)
* [ ] Query audit log: [issue](https://github.com/thanos-io/thanos/issues/1706) [prometheus](https://github.com/prometheus/prometheus/issues/6223)
* [ ] Unit test level benchmarks for both Querier and Store GW.
* [ ] e2e benchmark similar to [prombench](https://github.com/prometheus/prombench) [issue](https://github.com/thanos-io/thanos/issues/1707)

### Initiatives/Ideas 

* [ ] Improved panic handling in run group: [PR](https://github.com/thanos-io/thanos/pull/932)
* [ ] Eventual consistency handling between store GW and writers: [Proposal](https://github.com/thanos-io/thanos/pull/700), [Tracking issue](https://github.com/thanos-io/thanos/issues/564)
* [ ] Smooth partial upload logic for Compactor: [issue](https://github.com/thanos-io/thanos/issues/1335) 

## Downsampling

**Things to improve**  

* It still causes a bit of confusion e.g the purpose, cost and  usage e.g [rate[X]](https://github.com/thanos-io/thanos/issues/1115) 

### Initiatives/Ideas 

* [ ] Different query auto downsampling logic: [issue](https://github.com/thanos-io/thanos/issues/1170)
* [ ] Step based auto downsampling: [PR](https://github.com/thanos-io/thanos/pull/1465)
* [ ] Staleness + downsampling: [issue](https://github.com/thanos-io/thanos/issues/1433)

**Comment by bwplotka** [comment]
### Tried and rejected:

~* Simple global memory limiter in Querier.~ Rejected. [attempt](https://github.com/thanos-io/thanos/pull/1631)

**Comment by GiedriusS** [comment]
Not stale, very much a work in progress.

**Comment by bwplotka** [comment]
Let's close it. It was super not useful. Lesson learned. (: Milestones and separate issues works much better.
