### ISSUE TITLE
Incorporate new improvements from upstream in the React UI 

### ISSUE THREAD

**Issue by onprem** [thanos-io/thanos#3541]
In past few months there have been a sizable amount of UI related improvemnts in the upstream Prometheus code. A lot of those improvements make sense for Thanos as well.

Here's a list of PRs (in no specific order) that I think we should take a look at:
- [x] ~Fix styling bug for target labels with special names. prometheus/prometheus#7902~ Fixed in #3692
- [ ] Remove the need of `pathPrefix` in the React UI. prometheus/prometheus#7979
- [x] ~Add key to StatusWithStatusIndicator component in loop. prometheus/prometheus#6879~ Fixed in #3656 
- [x] ~Fix react UI bug with series going on and off. prometheus/prometheus#7804~ Fixed in #3693
- [ ] Support new duration format in graph range input. prometheus/prometheus#7833
- [x] ~Fix detail swatch glitch. prometheus/prometheus#7805~ Fixed in #3676
- [x] ~Fix button display when there is no panels. prometheus/prometheus#8155~ Fixed in #3694 
- [x] ~React UI: Change "metrics autocomplete" with "autocomplete". prometheus/prometheus#8174~ Fixed in #3575 

Most of these are pretty straightforward and small changes and should be easy for first time contributors.

**Comment by subhangi2731** [comment]
can you assign this issue to me @prmsrswt

**Comment by prmsrswt** [comment]
@subhangi2731 There are a lot of small tasks here, so you can pick something you'd like to work on and just comment here that you are working on it. That'll be sufficient to reduce duplicate efforts imo.

**Comment by soniasingla** [comment]
@prmsrswt 👋🏻

I am working on `Fix button display when there is no panels.` 🐈

**Comment by Namanl2001** [comment]
@prmsrswt I'll open a PR for ` Remove the need of pathPrefix in the React UI. ` soon.

**Comment by ajinkya359** [comment]
@prmsrswt I will work on the issue
`fix detail swatch glitch`

**Comment by ajinkya359** [comment]
I will open a PR for `Support new duration format in graph range input`

**Comment by yeya24** [comment]
This was closed by accident. Reopen it now.

**Comment by yeya24** [comment]
We also want to add the new editor. Should we add it here or open another issue?

**Comment by Namanl2001** [comment]
still valid
