### ISSUE TITLE
TODO points for 1.0

### ISSUE THREAD

**Issue by GiedriusS** [thanos-io/thanos#5635]
Let's release 1.0 finally at some point :tada: 

Some TODO points:

- [ ] https://github.com/thanos-io/thanos/pull/5607/files#diff-b484a14e04378ca9ecf288d24b5dd433576ff59e3e602734d3c568beb89bc456L58 convert all fields to millisecond precision
- [ ] Remove deprecated fields from protobufs && deprecated command line flags (https://github.com/thanos-io/thanos/search?q=deprecated)
- [ ] Remove deprecated `STACKDRIVER` tracing provider
- [ ] Remove `pkg/query/internal/test-storeset-pre-v0.8.0/storeset.go` ?

Maybe anything else?

**Comment by matej-g** [comment]
I wonder if we should also try to complete the deletion story somehow. Anecdotally, it seems a lot of users are asking about it (e.g. from yesterday https://cloud-native.slack.com/archives/CK5RSSC10/p1663695281723309) and we have couple of proposals in place to do this in store / compactor (https://github.com/thanos-io/thanos/issues/1598, https://github.com/thanos-io/thanos/pull/5436), but this work has not been finalized yet.

**Comment by GiedriusS** [comment]
Let's remove this field before 1.0 IMO https://github.com/thanos-io/thanos/pull/5709

**Comment by fpetkovski** [comment]
I've opened https://github.com/thanos-io/thanos/issues/5719 to discuss some dedup improvements. If we make any changes to StoreAPIs, it would be nice to introduce them prior to v1 and avoid maintaining code for backwards compatibility.
