### ISSUE TITLE
[Tracker] Distributed query execution tasks

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/thanos#6124]
This issue tracks the outstanding work needed to support distributed query execution.

- [ ] Implement a basic version of the distributed query execution mode: https://github.com/thanos-io/thanos/pull/6114
- [ ] Add support for injecting query parameters through the UI. This would include specifying auto-downsampling, store filtering and other parameters, similar to how we can do this now for regular Series calls.
- [ ] Add support for querier filtering based on external labels, analogous to store filtering in the store proxy.
- [ ] Modify the UI to show Queriers instead of Stores when distributed query mode is enabled.
- [ ]

**Comment by yeya24** [comment]
Is there any plan to embed the new query engine into sidecar, so that we can pushdown aggregations to Prometheus?

**Comment by fpetkovski** [comment]
The challenge with that is we won't properly do deduplication for HA pairs. We could embed it in a store but then the store has to have deduplicated blocks, or have all replicas of a given TSDB.

**Comment by prabhatkr007** [comment]
Hello @fpetkovski ,I would like to work on this as a LFx Mentorship Project.

I have some experience in Golang. I am looking to get more information and resources about Thanos project and this issue, to prepare for LFx Mentorship.

**Comment by AdiAkhileshSingh15** [comment]
Hey @fpetkovski ,
I'm interested in this project and I plan to apply as a Mentee once LFX Fall applications are open. 
Also, I'm curious to know if there are any beginner-friendly issues available for me to start contributing and get to know more about thanos.

Thanks a lot! Any help would be highly appreciated.

**Comment by sivasathyaseeelan** [comment]
Hi there, I am D N Siva Sathyaseelan pursuing my undergrad at IIT BHU (Indian Institute of Technology (BHU) Varanasi). I am highly interested in Open Source and Software Development. I would love to contribute to Thanos and participate in this LFX Fall'23!

**Comment by PranitPatil03** [comment]
Hello @fpetkovski 👋

I'm Pranit Patil, a student pursuing a Bachelor's degree in Computer Science at Mumbai University. Recently, I completed my internship at hubx.ai, where I worked as a full-stack developer intern. Prior to that, I gained experience as a front-end developer intern at Tech Cryptors.

My skills include JavaScript, ReactJS, Node, Express, MongoDB, and CSS libraries, such as Bootstrap. Through various projects, including full-stack ones, I have honed my expertise in full-stack development

I'm keen on participating in the LFX mentorship program and becoming an active community member. I kindly request your assistance in guiding me through project discussions.

Thank you.

**Comment by himanshuaggar** [comment]
Hi @fpetkovski  ,
I hope this message finds you in good health. I would really love to work with you and contribute to the CNCF - Thanos community for the LFX'23 Fall term. I have a solid understanding of various technologies such as React, NextJS, Typescript, MERN, React Native etc. I am enthusiastic about engaging in the LFX mentorship program and taking an active role within the community. I respectfully seek your guidance in leading me through project discussions.

Thanks!

**Comment by ishashankmittal** [comment]
Hi there @fpetkovski , I am Shashank Mittal pursuing my undergrad at IIT BHU (Indian Institute of Technology (BHU) Varanasi). I am highly interested in Open Source and Software Development. I would love to contribute to Thanos and participate in this LFX Fall'23!

**Comment by shrey-a-gupta** [comment]
Hi @fpetkovski , 

This is Shreya Gupta. I have recently done an internship at Ericsson, as an Automation Developer Intern, where I honed the skills of HTML, CSS, JavaScript, Groovy, Java, MySQL and Node.js.

I am willing to work with you and do some valuable work at Thanos for the LFX'23 Fall Term. I request you to assist me about the project through project discussions.

Looking forward to work with you, on this one !!

**Comment by triquenguyen** [comment]
Hi @fpetkovski 
I'm Trique Nguyen, currently a Software Engineering Undergraduate at San Jose State University. I would love to contribute to this project for the LFX Fall '23 term.
I am a full stack developer and have a domain in front-end development with React.js (also with TypeScript) along with other JavaScript frameworks and libraries such as Next.js, Framer Motion, Redux, and Vite, which I find significantly applicable to this open-source project for this term.
Recently, I have been learning Golang and I hope I can improve it through this project.
Thank you in advance!
