### ISSUE TITLE
Compact: Display TODO plan

### ISSUE THREAD

**Issue by SuperQ** [thanos-io/thanos#7285]
### Is your proposal related to a problem?

It is currently difficult to view what a Thanos Compact instance is currently working on.

### Describe the solution you'd like

In the Thanos Compact UI there is visibility of the global block list and loaded block list. But it would be useful to also have a list of planned and currently running compaction groups in order to see what exactly is in progress. This way it would be easier to diagnose what is currently happening, and possibly what is delaying the progress of compactions.

### Describe alternatives you've considered

It would also be useful to have this be part of the standard compact Info logging.

### Additional context

I have some clusters with very large blocks that need to be compacted, and it's impossible to know the progress of these large blocks.

**Comment by berryboylb** [comment]
Hello @cstyan, my name is Olorunfemi Daramola a software engineer. I'm interested in this project, is it still open?

**Comment by upsaurav12** [comment]
Hello Everyone,
I am Saurav Upadhyay, having some experience in React.js and Go(Not much but i am learning and trying to be good in go). I have Heard about Thanos and Prometheus have not much experience in it but will definitely learn them 

I am interested in this project as this will give me experience and will learn new things. Will apply for this project for upcoming LFX 2024 2nd term 
Thank you

**Comment by literalEval** [comment]
Hey @SuperQ 
Can you please point out to the pretest for this project ?

Thanks.

**Comment by 0xmihirsahu** [comment]
Hey @SuperQ 👋,

I'm Mihir Sahu, a full-stack developer specializing in **TypeScript**, **React**, and NextJS. I've worked with libraries such as Shadcn, RadixUI, Pro Components, and Leaflet, and I have experience with Figma. I have worked with Docker and Kubernetes. I'm excited about the opportunity to contribute to this project as it perfectly aligns with some of my skills and it will also make me learn new technologies. 

- [ ] Am I expert in GO?
- [ ] I'm learning GO
- [ ] Prior experience in working with Thanos and Prometheus
- [ ] Expertise in building UI with React

Participating in the LFX Mentorship program would be an invaluable experience for my professional growth. Looking forward to your guidance and the chance to collaborate.

Cheers!

**Comment by SuperQ** [comment]
> Can you please point out to the pretest for this project ?

What does this mean?

**Comment by MichaHoffmann** [comment]
We have an official way to apply for this project under this link: https://mentorship.lfx.linuxfoundation.org/project/05b3d261-f874-4b8c-bd7e-c4fa83c979b4

**Comment by literalEval** [comment]
> > Can you please point out to the pretest for this project ?
> 
> What does this mean?

Some LFX projects have some issues as pretests, which need to be done by the applicant to show their proficiency and understanding of the project. I was asking if such an issue exists for this project.

**Comment by saswatamcode** [comment]
Thanks for your interest everyone, @amandaguan-ag, will be picking this up as part of her LFX project! 🙂
